routes:
  /discounts:
    uses: DiscountsController@index
    as: discounts.index
  /discounts/create:
    uses: DiscountsController@create
    as: discounts.create
  post@/discounts:
    uses: DiscountsController@store
    as: discounts.store
  "/discounts/{discount}/edit":
    uses: DiscountsController@edit
    as: discounts.edit
  "post@/discounts/{discount}":
    uses: DiscountsController@update
    as: discounts.update

  /orders:
    uses: OrdersController@index
    as: orders.index
  /orders/create:
    uses: create
    as: orders.create
  post@/orders:
    uses: store
    as: orders.store
  "/orders/{order}/edit":
    uses: OrdersController@edit
    as: orders.edit
  "post@/orders/{order}":
    uses: update
    as: orders.update

  "post@/orders/{order}/items":
    uses: OrderItems@store
    as: order-items.store
